"""empty message

Revision ID: 2eaeebc135c4
Revises: 486eb11c9c70
Create Date: 2024-04-14 10:06:17.739117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaeebc135c4'
down_revision: Union[str, None] = '486eb11c9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_user_id_fkey', 'company', type_='foreignkey')
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('company_user_id_fkey', 'company', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
