"""empty message

Revision ID: 486eb11c9c70
Revises: 80c7057d0864
Create Date: 2024-04-14 09:25:20.664154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486eb11c9c70'
down_revision: Union[str, None] = '80c7057d0864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'company', 'users', ['owner_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'owner_id')
    # ### end Alembic commands ###
