"""empty message

Revision ID: 5e7c5ab82880
Revises: 2eaeebc135c4
Create Date: 2024-04-14 10:13:32.421468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7c5ab82880'
down_revision: Union[str, None] = '2eaeebc135c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('task_name', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'task_name')
    # ### end Alembic commands ###
