"""empty message

Revision ID: fc193dd43282
Revises: 
Create Date: 2024-04-14 04:29:16.735676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc193dd43282'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_time', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.Time(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_time', 'time',
               existing_type=sa.Time(timezone=True),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
